import Image from "next/image";
import Link from "next/link";
import Button from "../ui/Button";
import { formatDate, getPublishedPosts } from "@/lib/blog";

export default async function LatestInsights() {
  const featuredPosts = (await getPublishedPosts()).slice(0, 3);
  if (!featuredPosts.length) return null;
  return <section className="relative overflow-hidden bg-white py-16 md:py-24"><div className="pointer-events-none absolute right-0 top-0 h-96 w-96 rounded-full bg-brand-gold/5 blur-3xl" /><div className="container relative z-10 mx-auto px-4"><div className="mb-12 text-center md:mb-16"><span className="inline-block rounded-full border border-brand-gold/30 bg-brand-navy/5 px-3 py-1 text-xs font-bold uppercase tracking-widest text-brand-gold">Thought leadership</span><h2 className="mt-4 font-serif text-3xl text-brand-navy md:text-5xl">Latest Legal Insights</h2><div className="mx-auto mt-5 h-1 w-20 rounded-full bg-brand-gold" /><p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-neutral-600 md:text-lg">Authoritative legal analysis and courtroom strategy from our advocates in Chennai.</p></div><div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">{featuredPosts.map((post) => <article key={post.id}><Link href={`/blog/${post.slug}`} className="group block h-full"><div className="flex h-full flex-col overflow-hidden rounded-2xl border border-neutral-100 bg-neutral-50 shadow-sm transition-all hover:-translate-y-1 hover:shadow-xl"><div className="relative h-52 overflow-hidden"><Image src={post.coverImage} alt={post.coverAlt} fill className="object-cover transition-transform duration-500 group-hover:scale-105" sizes="(max-width: 768px) 100vw, 33vw" /><span className="absolute left-4 top-4 rounded-full bg-brand-navy/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{post.tags[0] || "Legal guide"}</span></div><div className="flex flex-grow flex-col p-6"><p className="text-xs text-neutral-500">{formatDate(post.publishedAt)} · {post.author}</p><h3 className="mt-3 font-serif text-xl font-bold leading-snug text-brand-navy group-hover:text-brand-gold">{post.title}</h3><p className="mt-3 flex-grow text-sm leading-relaxed text-neutral-600">{post.excerpt}</p><span className="mt-6 border-t border-neutral-200/60 pt-4 text-xs font-bold uppercase tracking-widest text-brand-navy group-hover:text-brand-gold">Read legal guide →</span></div></div></Link></article>)}</div><div className="mt-12 text-center"><Button href="/blog" variant="outline" size="lg" className="w-full justify-center sm:w-auto">Explore All Insights & Articles</Button></div></div></section>;
}
