"use client";

import { useEffect, useState } from "react";

type User = { id: string; email: string; full_name: string | null; role: "owner" | "advocate"; can_publish: boolean; active: boolean; created_at: string };

export default function AccessManager() {
  const [users, setUsers] = useState<User[]>([]);
  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"owner" | "advocate">("advocate");
  const [canPublish, setCanPublish] = useState(false);
  const [message, setMessage] = useState("");
  const load = async () => { const response = await fetch("/api/admin/users"); const data = await response.json(); setUsers(data.users || []); };
  useEffect(() => { load(); }, []);
  const invite = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch("/api/admin/users", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, role, canPublish }) }); const data = await response.json(); setMessage(response.ok ? `${email} can now sign in with Google.` : data.error || "Unable to add user."); if (response.ok) { setEmail(""); setRole("advocate"); setCanPublish(false); load(); } };
  const change = async (id: string, update: Record<string, unknown>) => { const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, ...update }) }); const data = await response.json(); setMessage(response.ok ? "Access updated." : data.error || "Unable to update access."); if (response.ok) load(); };
  return <>
    <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#b48b3d]">Owner controls</p><h1 className="mt-1 font-serif text-3xl text-[#12233f] md:text-4xl">Access & publishing rights</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-500">Only these email addresses can enter the editorial desk using Google. Owners decide whether each advocate may publish directly or must submit for review.</p></div>
    {message && <p className="mt-5 rounded-lg bg-[#e9e2d4] px-4 py-3 text-sm text-[#12233f]">{message}</p>}
    <form onSubmit={invite} className="mt-7 grid gap-4 rounded-2xl border border-[#ddd6c9] bg-white p-5 shadow-sm md:grid-cols-[1.5fr_.7fr_.8fr_auto] md:items-end"><label className="text-sm font-semibold text-[#12233f]">Google email<input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="advocate@gmail.com" className="mt-1.5 w-full rounded-lg border border-[#ded7ca] px-3 py-2.5 text-sm outline-none focus:border-[#c0a062]" /></label><label className="text-sm font-semibold text-[#12233f]">Role<select value={role} onChange={(event) => { const value = event.target.value as "owner" | "advocate"; setRole(value); if (value === "owner") setCanPublish(true); }} className="mt-1.5 w-full rounded-lg border border-[#ded7ca] bg-white px-3 py-2.5 text-sm outline-none focus:border-[#c0a062]"><option value="advocate">Advocate</option><option value="owner">Owner</option></select></label><label className="flex items-center gap-2 pb-3 text-sm font-semibold text-[#12233f]"><input type="checkbox" checked={canPublish} disabled={role === "owner"} onChange={(event) => setCanPublish(event.target.checked)} /> Direct publishing</label><button className="rounded-lg bg-[#12233f] px-4 py-3 text-sm font-bold text-white hover:bg-[#c0a062] hover:text-[#12233f]">Grant access</button></form>
    <section className="mt-7 overflow-hidden rounded-2xl border border-[#ddd6c9] bg-white shadow-sm"><div className="border-b border-[#eee9df] px-5 py-4"><h2 className="font-serif text-xl text-[#12233f]">Authorized people</h2></div><div className="divide-y divide-[#eee9df]">{users.map((user) => <article key={user.id} className="flex flex-col gap-4 px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="font-semibold text-[#12233f]">{user.full_name || user.email}</p><p className="text-sm text-slate-500">{user.full_name ? user.email : "Awaiting first Google sign-in"}</p></div><div className="flex flex-wrap items-center gap-2"><select value={user.role} onChange={(event) => change(user.id, { role: event.target.value })} className="rounded-lg border border-[#ded7ca] bg-white px-2 py-2 text-xs font-bold text-[#12233f]"><option value="advocate">Advocate</option><option value="owner">Owner</option></select><label className="flex items-center gap-1.5 rounded-lg border border-[#ded7ca] px-2 py-2 text-xs font-bold text-[#12233f]"><input type="checkbox" checked={user.can_publish} disabled={user.role === "owner"} onChange={(event) => change(user.id, { canPublish: event.target.checked })} /> Direct publish</label><button onClick={() => change(user.id, { active: !user.active })} className={`rounded-lg px-3 py-2 text-xs font-bold ${user.active ? "border border-rose-200 text-rose-700" : "bg-emerald-600 text-white"}`}>{user.active ? "Revoke" : "Restore"}</button></div></article>)}</div></section>
  </>;
}
